name: ElectronicWoodenFish
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 15.0  # 确保使用iOS 15.0作为最低部署目标

targets:
  ElectronicWoodenFish:
    type: application
    platform: iOS
    sources:
      - path: Sources
        includes:
          - "*.swift"
          - "Info.plist"
          - "Assets.xcassets"
      - path: Resources
        includes:
          - "*.mp3"
          - "*.wav"
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.electronicwoodenfish
        DEVELOPMENT_TEAM: ""  # 你可能需要设置你的开发者团队ID
        IPHONEOS_DEPLOYMENT_TARGET: 15.0
    info:
      path: Sources/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        CFBundleName: Electronic Wooden Fish
        UIApplicationSupportsIndirectInputEvents: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
